/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedMetronomeRouteImport } from './routes/_protected/metronome'
import { Route as ProtectedOfflineRouteImport } from './routes/_protected/offline'
import { Route as ProtectedPeopleRouteImport } from './routes/_protected/people'
import { Route as ProtectedReviewRouteImport } from './routes/_protected/review'
import { Route as ProtectedTunerRouteImport } from './routes/_protected/tuner'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as SetInviteTokenRouteImport } from './routes/set-invite.$token'
import { Route as TransferTokenRouteImport } from './routes/transfer.$token'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedAdminAuthRouteImport } from './routes/_protected/admin/auth'
import { Route as ProtectedAdminCatalogsRouteImport } from './routes/_protected/admin/catalogs'
import { Route as ProtectedAdminMetadataRouteImport } from './routes/_protected/admin/metadata'
import { Route as ProtectedAdminSecurityRouteImport } from './routes/_protected/admin/security'
import { Route as ProtectedAdminStemSeparationRouteImport } from './routes/_protected/admin/stem-separation'
import { Route as ProtectedAdminStorageRouteImport } from './routes/_protected/admin/storage'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedLibraryIndexRouteImport } from './routes/_protected/library/index'
import { Route as ProtectedLibrarySongVersionIdRouteImport } from './routes/_protected/library/$songVersionId'
import { Route as ProtectedLibraryArtistsRouteImport } from './routes/_protected/library/artists'
import { Route as ProtectedLibraryNewRouteImport } from './routes/_protected/library/new'
import { Route as ProtectedLibrarySongsRouteImport } from './routes/_protected/library/songs'
import { Route as ProtectedReviewIndexRouteImport } from './routes/_protected/review/index'
import { Route as ProtectedReviewSubmissionIdRouteImport } from './routes/_protected/review/$submissionId'
import { Route as ProtectedSetsIndexRouteImport } from './routes/_protected/sets/index'
import { Route as ProtectedSetsSetlistIdRouteImport } from './routes/_protected/sets/$setlistId'
import { Route as ProtectedSetsNewRouteImport } from './routes/_protected/sets/new'
import { Route as ProtectedSongbookCatalogsIndexRouteImport } from './routes/_protected/songbook-catalogs/index'
import { Route as ProtectedSongbookCatalogsCatalogIdRouteImport } from './routes/_protected/songbook-catalogs/$catalogId'
import { Route as ProtectedSongbookCatalogsNewRouteImport } from './routes/_protected/songbook-catalogs/new'
import { Route as ProtectedSongbooksIndexRouteImport } from './routes/_protected/songbooks/index'
import { Route as ProtectedSongbooksSongbookIdRouteImport } from './routes/_protected/songbooks/$songbookId'
import { Route as ProtectedSongbooksNewRouteImport } from './routes/_protected/songbooks/new'
import { Route as ProtectedTeamsIndexRouteImport } from './routes/_protected/teams/index'
import { Route as ProtectedTeamsTeamIdRouteImport } from './routes/_protected/teams/$teamId'
import { Route as ProtectedTeamsNewRouteImport } from './routes/_protected/teams/new'
import { Route as ProtectedLibrarySongVersionIdLiveRouteImport } from './routes/_protected/library/$songVersionId_.live'
import { Route as ProtectedLibraryArtistsNameRouteImport } from './routes/_protected/library/artists_.$name'
import { Route as ProtectedReviewSuggestionsSuggestionIdRouteImport } from './routes/_protected/review/suggestions.$suggestionId'
import { Route as ProtectedLibrarySongVersionIdArrangementsArrangementIdRouteImport } from './routes/_protected/library/$songVersionId_.arrangements.$arrangementId'
import { Route as ProtectedSetsSetlistIdLiveItemIdRouteImport } from './routes/_protected/sets/$setlistId_.live.$itemId'
import { Route as ProtectedSetsSetlistIdSongsItemIdRouteImport } from './routes/_protected/sets/$setlistId_.songs.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMetronomeRoute = ProtectedMetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOfflineRoute = ProtectedOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeopleRoute = ProtectedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReviewRoute = ProtectedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTunerRoute = ProtectedTunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => ProtectedRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SetInviteTokenRoute = SetInviteTokenRouteImport.update({
  id: '/set-invite/$token',
  path: '/set-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferTokenRoute = TransferTokenRouteImport.update({
  id: '/transfer/$token',
  path: '/transfer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminAuthRoute = ProtectedAdminAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminCatalogsRoute = ProtectedAdminCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminMetadataRoute = ProtectedAdminMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminSecurityRoute = ProtectedAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminStemSeparationRoute =
  ProtectedAdminStemSeparationRouteImport.update({
    id: '/stem-separation',
    path: '/stem-separation',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminStorageRoute = ProtectedAdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedLibraryIndexRoute = ProtectedLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibrarySongVersionIdRoute =
  ProtectedLibrarySongVersionIdRouteImport.update({
    id: '/library/$songVersionId',
    path: '/library/$songVersionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLibraryArtistsRoute = ProtectedLibraryArtistsRouteImport.update({
  id: '/library/artists',
  path: '/library/artists',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibraryNewRoute = ProtectedLibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibrarySongsRoute = ProtectedLibrarySongsRouteImport.update({
  id: '/library/songs',
  path: '/library/songs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReviewIndexRoute = ProtectedReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedReviewRoute,
} as any)
const ProtectedReviewSubmissionIdRoute =
  ProtectedReviewSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ProtectedReviewRoute,
  } as any)
const ProtectedSetsIndexRoute = ProtectedSetsIndexRouteImport.update({
  id: '/sets/',
  path: '/sets/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSetsSetlistIdRoute = ProtectedSetsSetlistIdRouteImport.update({
  id: '/sets/$setlistId',
  path: '/sets/$setlistId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSetsNewRoute = ProtectedSetsNewRouteImport.update({
  id: '/sets/new',
  path: '/sets/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSongbookCatalogsIndexRoute =
  ProtectedSongbookCatalogsIndexRouteImport.update({
    id: '/songbook-catalogs/',
    path: '/songbook-catalogs/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbookCatalogsCatalogIdRoute =
  ProtectedSongbookCatalogsCatalogIdRouteImport.update({
    id: '/songbook-catalogs/$catalogId',
    path: '/songbook-catalogs/$catalogId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbookCatalogsNewRoute =
  ProtectedSongbookCatalogsNewRouteImport.update({
    id: '/songbook-catalogs/new',
    path: '/songbook-catalogs/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbooksIndexRoute = ProtectedSongbooksIndexRouteImport.update({
  id: '/songbooks/',
  path: '/songbooks/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSongbooksSongbookIdRoute =
  ProtectedSongbooksSongbookIdRouteImport.update({
    id: '/songbooks/$songbookId',
    path: '/songbooks/$songbookId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbooksNewRoute = ProtectedSongbooksNewRouteImport.update({
  id: '/songbooks/new',
  path: '/songbooks/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsIndexRoute = ProtectedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsTeamIdRoute = ProtectedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsNewRoute = ProtectedTeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibrarySongVersionIdLiveRoute =
  ProtectedLibrarySongVersionIdLiveRouteImport.update({
    id: '/library/$songVersionId_/live',
    path: '/library/$songVersionId/live',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLibraryArtistsNameRoute =
  ProtectedLibraryArtistsNameRouteImport.update({
    id: '/library/artists_/$name',
    path: '/library/artists/$name',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReviewSuggestionsSuggestionIdRoute =
  ProtectedReviewSuggestionsSuggestionIdRouteImport.update({
    id: '/suggestions/$suggestionId',
    path: '/suggestions/$suggestionId',
    getParentRoute: () => ProtectedReviewRoute,
  } as any)
const ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute =
  ProtectedLibrarySongVersionIdArrangementsArrangementIdRouteImport.update({
    id: '/library/$songVersionId_/arrangements/$arrangementId',
    path: '/library/$songVersionId/arrangements/$arrangementId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSetsSetlistIdLiveItemIdRoute =
  ProtectedSetsSetlistIdLiveItemIdRouteImport.update({
    id: '/sets/$setlistId_/live/$itemId',
    path: '/sets/$setlistId/live/$itemId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSetsSetlistIdSongsItemIdRoute =
  ProtectedSetsSetlistIdSongsItemIdRouteImport.update({
    id: '/sets/$setlistId_/songs/$itemId',
    path: '/sets/$setlistId/songs/$itemId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof ProtectedAccountRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/metronome': typeof ProtectedMetronomeRoute
  '/offline': typeof ProtectedOfflineRoute
  '/people': typeof ProtectedPeopleRoute
  '/review': typeof ProtectedReviewRouteWithChildren
  '/tuner': typeof ProtectedTunerRoute
  '/join/$token': typeof JoinTokenRoute
  '/set-invite/$token': typeof SetInviteTokenRoute
  '/transfer/$token': typeof TransferTokenRoute
  '/admin/auth': typeof ProtectedAdminAuthRoute
  '/admin/catalogs': typeof ProtectedAdminCatalogsRoute
  '/admin/metadata': typeof ProtectedAdminMetadataRoute
  '/admin/security': typeof ProtectedAdminSecurityRoute
  '/admin/stem-separation': typeof ProtectedAdminStemSeparationRoute
  '/admin/storage': typeof ProtectedAdminStorageRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/library/artists': typeof ProtectedLibraryArtistsRoute
  '/library/new': typeof ProtectedLibraryNewRoute
  '/library/songs': typeof ProtectedLibrarySongsRoute
  '/review/$submissionId': typeof ProtectedReviewSubmissionIdRoute
  '/sets/$setlistId': typeof ProtectedSetsSetlistIdRoute
  '/sets/new': typeof ProtectedSetsNewRoute
  '/songbook-catalogs/$catalogId': typeof ProtectedSongbookCatalogsCatalogIdRoute
  '/songbook-catalogs/new': typeof ProtectedSongbookCatalogsNewRoute
  '/songbooks/$songbookId': typeof ProtectedSongbooksSongbookIdRoute
  '/songbooks/new': typeof ProtectedSongbooksNewRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/library/': typeof ProtectedLibraryIndexRoute
  '/review/': typeof ProtectedReviewIndexRoute
  '/sets/': typeof ProtectedSetsIndexRoute
  '/songbook-catalogs/': typeof ProtectedSongbookCatalogsIndexRoute
  '/songbooks/': typeof ProtectedSongbooksIndexRoute
  '/teams/': typeof ProtectedTeamsIndexRoute
  '/library/$songVersionId/live': typeof ProtectedLibrarySongVersionIdLiveRoute
  '/library/artists/$name': typeof ProtectedLibraryArtistsNameRoute
  '/review/suggestions/$suggestionId': typeof ProtectedReviewSuggestionsSuggestionIdRoute
  '/library/$songVersionId/arrangements/$arrangementId': typeof ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute
  '/sets/$setlistId/live/$itemId': typeof ProtectedSetsSetlistIdLiveItemIdRoute
  '/sets/$setlistId/songs/$itemId': typeof ProtectedSetsSetlistIdSongsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/metronome': typeof ProtectedMetronomeRoute
  '/offline': typeof ProtectedOfflineRoute
  '/people': typeof ProtectedPeopleRoute
  '/tuner': typeof ProtectedTunerRoute
  '/join/$token': typeof JoinTokenRoute
  '/set-invite/$token': typeof SetInviteTokenRoute
  '/transfer/$token': typeof TransferTokenRoute
  '/admin/auth': typeof ProtectedAdminAuthRoute
  '/admin/catalogs': typeof ProtectedAdminCatalogsRoute
  '/admin/metadata': typeof ProtectedAdminMetadataRoute
  '/admin/security': typeof ProtectedAdminSecurityRoute
  '/admin/stem-separation': typeof ProtectedAdminStemSeparationRoute
  '/admin/storage': typeof ProtectedAdminStorageRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/library/artists': typeof ProtectedLibraryArtistsRoute
  '/library/new': typeof ProtectedLibraryNewRoute
  '/library/songs': typeof ProtectedLibrarySongsRoute
  '/review/$submissionId': typeof ProtectedReviewSubmissionIdRoute
  '/sets/$setlistId': typeof ProtectedSetsSetlistIdRoute
  '/sets/new': typeof ProtectedSetsNewRoute
  '/songbook-catalogs/$catalogId': typeof ProtectedSongbookCatalogsCatalogIdRoute
  '/songbook-catalogs/new': typeof ProtectedSongbookCatalogsNewRoute
  '/songbooks/$songbookId': typeof ProtectedSongbooksSongbookIdRoute
  '/songbooks/new': typeof ProtectedSongbooksNewRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/library': typeof ProtectedLibraryIndexRoute
  '/review': typeof ProtectedReviewIndexRoute
  '/sets': typeof ProtectedSetsIndexRoute
  '/songbook-catalogs': typeof ProtectedSongbookCatalogsIndexRoute
  '/songbooks': typeof ProtectedSongbooksIndexRoute
  '/teams': typeof ProtectedTeamsIndexRoute
  '/library/$songVersionId/live': typeof ProtectedLibrarySongVersionIdLiveRoute
  '/library/artists/$name': typeof ProtectedLibraryArtistsNameRoute
  '/review/suggestions/$suggestionId': typeof ProtectedReviewSuggestionsSuggestionIdRoute
  '/library/$songVersionId/arrangements/$arrangementId': typeof ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute
  '/sets/$setlistId/live/$itemId': typeof ProtectedSetsSetlistIdLiveItemIdRoute
  '/sets/$setlistId/songs/$itemId': typeof ProtectedSetsSetlistIdSongsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/metronome': typeof ProtectedMetronomeRoute
  '/_protected/offline': typeof ProtectedOfflineRoute
  '/_protected/people': typeof ProtectedPeopleRoute
  '/_protected/review': typeof ProtectedReviewRouteWithChildren
  '/_protected/tuner': typeof ProtectedTunerRoute
  '/join/$token': typeof JoinTokenRoute
  '/set-invite/$token': typeof SetInviteTokenRoute
  '/transfer/$token': typeof TransferTokenRoute
  '/_protected/admin/auth': typeof ProtectedAdminAuthRoute
  '/_protected/admin/catalogs': typeof ProtectedAdminCatalogsRoute
  '/_protected/admin/metadata': typeof ProtectedAdminMetadataRoute
  '/_protected/admin/security': typeof ProtectedAdminSecurityRoute
  '/_protected/admin/stem-separation': typeof ProtectedAdminStemSeparationRoute
  '/_protected/admin/storage': typeof ProtectedAdminStorageRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/_protected/library/artists': typeof ProtectedLibraryArtistsRoute
  '/_protected/library/new': typeof ProtectedLibraryNewRoute
  '/_protected/library/songs': typeof ProtectedLibrarySongsRoute
  '/_protected/review/$submissionId': typeof ProtectedReviewSubmissionIdRoute
  '/_protected/sets/$setlistId': typeof ProtectedSetsSetlistIdRoute
  '/_protected/sets/new': typeof ProtectedSetsNewRoute
  '/_protected/songbook-catalogs/$catalogId': typeof ProtectedSongbookCatalogsCatalogIdRoute
  '/_protected/songbook-catalogs/new': typeof ProtectedSongbookCatalogsNewRoute
  '/_protected/songbooks/$songbookId': typeof ProtectedSongbooksSongbookIdRoute
  '/_protected/songbooks/new': typeof ProtectedSongbooksNewRoute
  '/_protected/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/_protected/teams/new': typeof ProtectedTeamsNewRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/library/': typeof ProtectedLibraryIndexRoute
  '/_protected/review/': typeof ProtectedReviewIndexRoute
  '/_protected/sets/': typeof ProtectedSetsIndexRoute
  '/_protected/songbook-catalogs/': typeof ProtectedSongbookCatalogsIndexRoute
  '/_protected/songbooks/': typeof ProtectedSongbooksIndexRoute
  '/_protected/teams/': typeof ProtectedTeamsIndexRoute
  '/_protected/library/$songVersionId_/live': typeof ProtectedLibrarySongVersionIdLiveRoute
  '/_protected/library/artists_/$name': typeof ProtectedLibraryArtistsNameRoute
  '/_protected/review/suggestions/$suggestionId': typeof ProtectedReviewSuggestionsSuggestionIdRoute
  '/_protected/library/$songVersionId_/arrangements/$arrangementId': typeof ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute
  '/_protected/sets/$setlistId_/live/$itemId': typeof ProtectedSetsSetlistIdLiveItemIdRoute
  '/_protected/sets/$setlistId_/songs/$itemId': typeof ProtectedSetsSetlistIdSongsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/metronome'
    | '/offline'
    | '/people'
    | '/review'
    | '/tuner'
    | '/join/$token'
    | '/set-invite/$token'
    | '/transfer/$token'
    | '/admin/auth'
    | '/admin/catalogs'
    | '/admin/metadata'
    | '/admin/security'
    | '/admin/stem-separation'
    | '/admin/storage'
    | '/admin/users'
    | '/library/$songVersionId'
    | '/library/artists'
    | '/library/new'
    | '/library/songs'
    | '/review/$submissionId'
    | '/sets/$setlistId'
    | '/sets/new'
    | '/songbook-catalogs/$catalogId'
    | '/songbook-catalogs/new'
    | '/songbooks/$songbookId'
    | '/songbooks/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/admin/'
    | '/library/'
    | '/review/'
    | '/sets/'
    | '/songbook-catalogs/'
    | '/songbooks/'
    | '/teams/'
    | '/library/$songVersionId/live'
    | '/library/artists/$name'
    | '/review/suggestions/$suggestionId'
    | '/library/$songVersionId/arrangements/$arrangementId'
    | '/sets/$setlistId/live/$itemId'
    | '/sets/$setlistId/songs/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/account'
    | '/dashboard'
    | '/metronome'
    | '/offline'
    | '/people'
    | '/tuner'
    | '/join/$token'
    | '/set-invite/$token'
    | '/transfer/$token'
    | '/admin/auth'
    | '/admin/catalogs'
    | '/admin/metadata'
    | '/admin/security'
    | '/admin/stem-separation'
    | '/admin/storage'
    | '/admin/users'
    | '/library/$songVersionId'
    | '/library/artists'
    | '/library/new'
    | '/library/songs'
    | '/review/$submissionId'
    | '/sets/$setlistId'
    | '/sets/new'
    | '/songbook-catalogs/$catalogId'
    | '/songbook-catalogs/new'
    | '/songbooks/$songbookId'
    | '/songbooks/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/admin'
    | '/library'
    | '/review'
    | '/sets'
    | '/songbook-catalogs'
    | '/songbooks'
    | '/teams'
    | '/library/$songVersionId/live'
    | '/library/artists/$name'
    | '/review/suggestions/$suggestionId'
    | '/library/$songVersionId/arrangements/$arrangementId'
    | '/sets/$setlistId/live/$itemId'
    | '/sets/$setlistId/songs/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/reset-password'
    | '/_protected/account'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/metronome'
    | '/_protected/offline'
    | '/_protected/people'
    | '/_protected/review'
    | '/_protected/tuner'
    | '/join/$token'
    | '/set-invite/$token'
    | '/transfer/$token'
    | '/_protected/admin/auth'
    | '/_protected/admin/catalogs'
    | '/_protected/admin/metadata'
    | '/_protected/admin/security'
    | '/_protected/admin/stem-separation'
    | '/_protected/admin/storage'
    | '/_protected/admin/users'
    | '/_protected/library/$songVersionId'
    | '/_protected/library/artists'
    | '/_protected/library/new'
    | '/_protected/library/songs'
    | '/_protected/review/$submissionId'
    | '/_protected/sets/$setlistId'
    | '/_protected/sets/new'
    | '/_protected/songbook-catalogs/$catalogId'
    | '/_protected/songbook-catalogs/new'
    | '/_protected/songbooks/$songbookId'
    | '/_protected/songbooks/new'
    | '/_protected/teams/$teamId'
    | '/_protected/teams/new'
    | '/_protected/admin/'
    | '/_protected/library/'
    | '/_protected/review/'
    | '/_protected/sets/'
    | '/_protected/songbook-catalogs/'
    | '/_protected/songbooks/'
    | '/_protected/teams/'
    | '/_protected/library/$songVersionId_/live'
    | '/_protected/library/artists_/$name'
    | '/_protected/review/suggestions/$suggestionId'
    | '/_protected/library/$songVersionId_/arrangements/$arrangementId'
    | '/_protected/sets/$setlistId_/live/$itemId'
    | '/_protected/sets/$setlistId_/songs/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SetInviteTokenRoute: typeof SetInviteTokenRoute
  TransferTokenRoute: typeof TransferTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/metronome': {
      id: '/_protected/metronome'
      path: '/metronome'
      fullPath: '/metronome'
      preLoaderRoute: typeof ProtectedMetronomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/offline': {
      id: '/_protected/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof ProtectedOfflineRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people': {
      id: '/_protected/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ProtectedPeopleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/review': {
      id: '/_protected/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ProtectedReviewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tuner': {
      id: '/_protected/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof ProtectedTunerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-invite/$token': {
      id: '/set-invite/$token'
      path: '/set-invite/$token'
      fullPath: '/set-invite/$token'
      preLoaderRoute: typeof SetInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer/$token': {
      id: '/transfer/$token'
      path: '/transfer/$token'
      fullPath: '/transfer/$token'
      preLoaderRoute: typeof TransferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/auth': {
      id: '/_protected/admin/auth'
      path: '/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof ProtectedAdminAuthRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/catalogs': {
      id: '/_protected/admin/catalogs'
      path: '/catalogs'
      fullPath: '/admin/catalogs'
      preLoaderRoute: typeof ProtectedAdminCatalogsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/metadata': {
      id: '/_protected/admin/metadata'
      path: '/metadata'
      fullPath: '/admin/metadata'
      preLoaderRoute: typeof ProtectedAdminMetadataRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/security': {
      id: '/_protected/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof ProtectedAdminSecurityRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/stem-separation': {
      id: '/_protected/admin/stem-separation'
      path: '/stem-separation'
      fullPath: '/admin/stem-separation'
      preLoaderRoute: typeof ProtectedAdminStemSeparationRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/storage': {
      id: '/_protected/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof ProtectedAdminStorageRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/library/': {
      id: '/_protected/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof ProtectedLibraryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/$songVersionId': {
      id: '/_protected/library/$songVersionId'
      path: '/library/$songVersionId'
      fullPath: '/library/$songVersionId'
      preLoaderRoute: typeof ProtectedLibrarySongVersionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/artists': {
      id: '/_protected/library/artists'
      path: '/library/artists'
      fullPath: '/library/artists'
      preLoaderRoute: typeof ProtectedLibraryArtistsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/new': {
      id: '/_protected/library/new'
      path: '/library/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof ProtectedLibraryNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/songs': {
      id: '/_protected/library/songs'
      path: '/library/songs'
      fullPath: '/library/songs'
      preLoaderRoute: typeof ProtectedLibrarySongsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/review/': {
      id: '/_protected/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ProtectedReviewIndexRouteImport
      parentRoute: typeof ProtectedReviewRoute
    }
    '/_protected/review/$submissionId': {
      id: '/_protected/review/$submissionId'
      path: '/$submissionId'
      fullPath: '/review/$submissionId'
      preLoaderRoute: typeof ProtectedReviewSubmissionIdRouteImport
      parentRoute: typeof ProtectedReviewRoute
    }
    '/_protected/sets/': {
      id: '/_protected/sets/'
      path: '/sets'
      fullPath: '/sets/'
      preLoaderRoute: typeof ProtectedSetsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sets/$setlistId': {
      id: '/_protected/sets/$setlistId'
      path: '/sets/$setlistId'
      fullPath: '/sets/$setlistId'
      preLoaderRoute: typeof ProtectedSetsSetlistIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sets/new': {
      id: '/_protected/sets/new'
      path: '/sets/new'
      fullPath: '/sets/new'
      preLoaderRoute: typeof ProtectedSetsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbook-catalogs/': {
      id: '/_protected/songbook-catalogs/'
      path: '/songbook-catalogs'
      fullPath: '/songbook-catalogs/'
      preLoaderRoute: typeof ProtectedSongbookCatalogsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbook-catalogs/$catalogId': {
      id: '/_protected/songbook-catalogs/$catalogId'
      path: '/songbook-catalogs/$catalogId'
      fullPath: '/songbook-catalogs/$catalogId'
      preLoaderRoute: typeof ProtectedSongbookCatalogsCatalogIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbook-catalogs/new': {
      id: '/_protected/songbook-catalogs/new'
      path: '/songbook-catalogs/new'
      fullPath: '/songbook-catalogs/new'
      preLoaderRoute: typeof ProtectedSongbookCatalogsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbooks/': {
      id: '/_protected/songbooks/'
      path: '/songbooks'
      fullPath: '/songbooks/'
      preLoaderRoute: typeof ProtectedSongbooksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbooks/$songbookId': {
      id: '/_protected/songbooks/$songbookId'
      path: '/songbooks/$songbookId'
      fullPath: '/songbooks/$songbookId'
      preLoaderRoute: typeof ProtectedSongbooksSongbookIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbooks/new': {
      id: '/_protected/songbooks/new'
      path: '/songbooks/new'
      fullPath: '/songbooks/new'
      preLoaderRoute: typeof ProtectedSongbooksNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/': {
      id: '/_protected/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof ProtectedTeamsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/$teamId': {
      id: '/_protected/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof ProtectedTeamsTeamIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/new': {
      id: '/_protected/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof ProtectedTeamsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/$songVersionId_/live': {
      id: '/_protected/library/$songVersionId_/live'
      path: '/library/$songVersionId/live'
      fullPath: '/library/$songVersionId/live'
      preLoaderRoute: typeof ProtectedLibrarySongVersionIdLiveRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/artists_/$name': {
      id: '/_protected/library/artists_/$name'
      path: '/library/artists/$name'
      fullPath: '/library/artists/$name'
      preLoaderRoute: typeof ProtectedLibraryArtistsNameRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/review/suggestions/$suggestionId': {
      id: '/_protected/review/suggestions/$suggestionId'
      path: '/suggestions/$suggestionId'
      fullPath: '/review/suggestions/$suggestionId'
      preLoaderRoute: typeof ProtectedReviewSuggestionsSuggestionIdRouteImport
      parentRoute: typeof ProtectedReviewRoute
    }
    '/_protected/library/$songVersionId_/arrangements/$arrangementId': {
      id: '/_protected/library/$songVersionId_/arrangements/$arrangementId'
      path: '/library/$songVersionId/arrangements/$arrangementId'
      fullPath: '/library/$songVersionId/arrangements/$arrangementId'
      preLoaderRoute: typeof ProtectedLibrarySongVersionIdArrangementsArrangementIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sets/$setlistId_/live/$itemId': {
      id: '/_protected/sets/$setlistId_/live/$itemId'
      path: '/sets/$setlistId/live/$itemId'
      fullPath: '/sets/$setlistId/live/$itemId'
      preLoaderRoute: typeof ProtectedSetsSetlistIdLiveItemIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/sets/$setlistId_/songs/$itemId': {
      id: '/_protected/sets/$setlistId_/songs/$itemId'
      path: '/sets/$setlistId/songs/$itemId'
      fullPath: '/sets/$setlistId/songs/$itemId'
      preLoaderRoute: typeof ProtectedSetsSetlistIdSongsItemIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminAuthRoute: typeof ProtectedAdminAuthRoute
  ProtectedAdminCatalogsRoute: typeof ProtectedAdminCatalogsRoute
  ProtectedAdminMetadataRoute: typeof ProtectedAdminMetadataRoute
  ProtectedAdminSecurityRoute: typeof ProtectedAdminSecurityRoute
  ProtectedAdminStemSeparationRoute: typeof ProtectedAdminStemSeparationRoute
  ProtectedAdminStorageRoute: typeof ProtectedAdminStorageRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAuthRoute: ProtectedAdminAuthRoute,
  ProtectedAdminCatalogsRoute: ProtectedAdminCatalogsRoute,
  ProtectedAdminMetadataRoute: ProtectedAdminMetadataRoute,
  ProtectedAdminSecurityRoute: ProtectedAdminSecurityRoute,
  ProtectedAdminStemSeparationRoute: ProtectedAdminStemSeparationRoute,
  ProtectedAdminStorageRoute: ProtectedAdminStorageRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedReviewRouteChildren {
  ProtectedReviewSubmissionIdRoute: typeof ProtectedReviewSubmissionIdRoute
  ProtectedReviewIndexRoute: typeof ProtectedReviewIndexRoute
  ProtectedReviewSuggestionsSuggestionIdRoute: typeof ProtectedReviewSuggestionsSuggestionIdRoute
}

const ProtectedReviewRouteChildren: ProtectedReviewRouteChildren = {
  ProtectedReviewSubmissionIdRoute: ProtectedReviewSubmissionIdRoute,
  ProtectedReviewIndexRoute: ProtectedReviewIndexRoute,
  ProtectedReviewSuggestionsSuggestionIdRoute:
    ProtectedReviewSuggestionsSuggestionIdRoute,
}

const ProtectedReviewRouteWithChildren = ProtectedReviewRoute._addFileChildren(
  ProtectedReviewRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMetronomeRoute: typeof ProtectedMetronomeRoute
  ProtectedOfflineRoute: typeof ProtectedOfflineRoute
  ProtectedPeopleRoute: typeof ProtectedPeopleRoute
  ProtectedReviewRoute: typeof ProtectedReviewRouteWithChildren
  ProtectedTunerRoute: typeof ProtectedTunerRoute
  ProtectedLibrarySongVersionIdRoute: typeof ProtectedLibrarySongVersionIdRoute
  ProtectedLibraryArtistsRoute: typeof ProtectedLibraryArtistsRoute
  ProtectedLibraryNewRoute: typeof ProtectedLibraryNewRoute
  ProtectedLibrarySongsRoute: typeof ProtectedLibrarySongsRoute
  ProtectedSetsSetlistIdRoute: typeof ProtectedSetsSetlistIdRoute
  ProtectedSetsNewRoute: typeof ProtectedSetsNewRoute
  ProtectedSongbookCatalogsCatalogIdRoute: typeof ProtectedSongbookCatalogsCatalogIdRoute
  ProtectedSongbookCatalogsNewRoute: typeof ProtectedSongbookCatalogsNewRoute
  ProtectedSongbooksSongbookIdRoute: typeof ProtectedSongbooksSongbookIdRoute
  ProtectedSongbooksNewRoute: typeof ProtectedSongbooksNewRoute
  ProtectedTeamsTeamIdRoute: typeof ProtectedTeamsTeamIdRoute
  ProtectedTeamsNewRoute: typeof ProtectedTeamsNewRoute
  ProtectedLibraryIndexRoute: typeof ProtectedLibraryIndexRoute
  ProtectedSetsIndexRoute: typeof ProtectedSetsIndexRoute
  ProtectedSongbookCatalogsIndexRoute: typeof ProtectedSongbookCatalogsIndexRoute
  ProtectedSongbooksIndexRoute: typeof ProtectedSongbooksIndexRoute
  ProtectedTeamsIndexRoute: typeof ProtectedTeamsIndexRoute
  ProtectedLibrarySongVersionIdLiveRoute: typeof ProtectedLibrarySongVersionIdLiveRoute
  ProtectedLibraryArtistsNameRoute: typeof ProtectedLibraryArtistsNameRoute
  ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute: typeof ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute
  ProtectedSetsSetlistIdLiveItemIdRoute: typeof ProtectedSetsSetlistIdLiveItemIdRoute
  ProtectedSetsSetlistIdSongsItemIdRoute: typeof ProtectedSetsSetlistIdSongsItemIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMetronomeRoute: ProtectedMetronomeRoute,
  ProtectedOfflineRoute: ProtectedOfflineRoute,
  ProtectedPeopleRoute: ProtectedPeopleRoute,
  ProtectedReviewRoute: ProtectedReviewRouteWithChildren,
  ProtectedTunerRoute: ProtectedTunerRoute,
  ProtectedLibrarySongVersionIdRoute: ProtectedLibrarySongVersionIdRoute,
  ProtectedLibraryArtistsRoute: ProtectedLibraryArtistsRoute,
  ProtectedLibraryNewRoute: ProtectedLibraryNewRoute,
  ProtectedLibrarySongsRoute: ProtectedLibrarySongsRoute,
  ProtectedSetsSetlistIdRoute: ProtectedSetsSetlistIdRoute,
  ProtectedSetsNewRoute: ProtectedSetsNewRoute,
  ProtectedSongbookCatalogsCatalogIdRoute:
    ProtectedSongbookCatalogsCatalogIdRoute,
  ProtectedSongbookCatalogsNewRoute: ProtectedSongbookCatalogsNewRoute,
  ProtectedSongbooksSongbookIdRoute: ProtectedSongbooksSongbookIdRoute,
  ProtectedSongbooksNewRoute: ProtectedSongbooksNewRoute,
  ProtectedTeamsTeamIdRoute: ProtectedTeamsTeamIdRoute,
  ProtectedTeamsNewRoute: ProtectedTeamsNewRoute,
  ProtectedLibraryIndexRoute: ProtectedLibraryIndexRoute,
  ProtectedSetsIndexRoute: ProtectedSetsIndexRoute,
  ProtectedSongbookCatalogsIndexRoute: ProtectedSongbookCatalogsIndexRoute,
  ProtectedSongbooksIndexRoute: ProtectedSongbooksIndexRoute,
  ProtectedTeamsIndexRoute: ProtectedTeamsIndexRoute,
  ProtectedLibrarySongVersionIdLiveRoute:
    ProtectedLibrarySongVersionIdLiveRoute,
  ProtectedLibraryArtistsNameRoute: ProtectedLibraryArtistsNameRoute,
  ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute:
    ProtectedLibrarySongVersionIdArrangementsArrangementIdRoute,
  ProtectedSetsSetlistIdLiveItemIdRoute: ProtectedSetsSetlistIdLiveItemIdRoute,
  ProtectedSetsSetlistIdSongsItemIdRoute:
    ProtectedSetsSetlistIdSongsItemIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  JoinTokenRoute: JoinTokenRoute,
  SetInviteTokenRoute: SetInviteTokenRoute,
  TransferTokenRoute: TransferTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
