/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ProtectedLibraryIndexRouteImport } from './routes/_protected/library/index'
import { Route as ProtectedLibrarySongVersionIdRouteImport } from './routes/_protected/library/$songVersionId'
import { Route as ProtectedLibraryNewRouteImport } from './routes/_protected/library/new'
import { Route as ProtectedSongbookCatalogsIndexRouteImport } from './routes/_protected/songbook-catalogs/index'
import { Route as ProtectedSongbookCatalogsCatalogIdRouteImport } from './routes/_protected/songbook-catalogs/$catalogId'
import { Route as ProtectedSongbookCatalogsNewRouteImport } from './routes/_protected/songbook-catalogs/new'
import { Route as ProtectedSongbooksIndexRouteImport } from './routes/_protected/songbooks/index'
import { Route as ProtectedSongbooksSongbookIdRouteImport } from './routes/_protected/songbooks/$songbookId'
import { Route as ProtectedSongbooksNewRouteImport } from './routes/_protected/songbooks/new'
import { Route as ProtectedTeamsTeamIdRouteImport } from './routes/_protected/teams/$teamId'
import { Route as ProtectedTeamsNewRouteImport } from './routes/_protected/teams/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLibraryIndexRoute = ProtectedLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibrarySongVersionIdRoute =
  ProtectedLibrarySongVersionIdRouteImport.update({
    id: '/library/$songVersionId',
    path: '/library/$songVersionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLibraryNewRoute = ProtectedLibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSongbookCatalogsIndexRoute =
  ProtectedSongbookCatalogsIndexRouteImport.update({
    id: '/songbook-catalogs/',
    path: '/songbook-catalogs/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbookCatalogsCatalogIdRoute =
  ProtectedSongbookCatalogsCatalogIdRouteImport.update({
    id: '/songbook-catalogs/$catalogId',
    path: '/songbook-catalogs/$catalogId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbookCatalogsNewRoute =
  ProtectedSongbookCatalogsNewRouteImport.update({
    id: '/songbook-catalogs/new',
    path: '/songbook-catalogs/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbooksIndexRoute = ProtectedSongbooksIndexRouteImport.update({
  id: '/songbooks/',
  path: '/songbooks/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSongbooksSongbookIdRoute =
  ProtectedSongbooksSongbookIdRouteImport.update({
    id: '/songbooks/$songbookId',
    path: '/songbooks/$songbookId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSongbooksNewRoute = ProtectedSongbooksNewRouteImport.update({
  id: '/songbooks/new',
  path: '/songbooks/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsTeamIdRoute = ProtectedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamsNewRoute = ProtectedTeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/join/$token': typeof JoinTokenRoute
  '/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/library/new': typeof ProtectedLibraryNewRoute
  '/songbook-catalogs/$catalogId': typeof ProtectedSongbookCatalogsCatalogIdRoute
  '/songbook-catalogs/new': typeof ProtectedSongbookCatalogsNewRoute
  '/songbooks/$songbookId': typeof ProtectedSongbooksSongbookIdRoute
  '/songbooks/new': typeof ProtectedSongbooksNewRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/': typeof ProtectedLibraryIndexRoute
  '/songbook-catalogs/': typeof ProtectedSongbookCatalogsIndexRoute
  '/songbooks/': typeof ProtectedSongbooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/join/$token': typeof JoinTokenRoute
  '/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/library/new': typeof ProtectedLibraryNewRoute
  '/songbook-catalogs/$catalogId': typeof ProtectedSongbookCatalogsCatalogIdRoute
  '/songbook-catalogs/new': typeof ProtectedSongbookCatalogsNewRoute
  '/songbooks/$songbookId': typeof ProtectedSongbooksSongbookIdRoute
  '/songbooks/new': typeof ProtectedSongbooksNewRoute
  '/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library': typeof ProtectedLibraryIndexRoute
  '/songbook-catalogs': typeof ProtectedSongbookCatalogsIndexRoute
  '/songbooks': typeof ProtectedSongbooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/join/$token': typeof JoinTokenRoute
  '/_protected/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/_protected/library/new': typeof ProtectedLibraryNewRoute
  '/_protected/songbook-catalogs/$catalogId': typeof ProtectedSongbookCatalogsCatalogIdRoute
  '/_protected/songbook-catalogs/new': typeof ProtectedSongbookCatalogsNewRoute
  '/_protected/songbooks/$songbookId': typeof ProtectedSongbooksSongbookIdRoute
  '/_protected/songbooks/new': typeof ProtectedSongbooksNewRoute
  '/_protected/teams/$teamId': typeof ProtectedTeamsTeamIdRoute
  '/_protected/teams/new': typeof ProtectedTeamsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/library/': typeof ProtectedLibraryIndexRoute
  '/_protected/songbook-catalogs/': typeof ProtectedSongbookCatalogsIndexRoute
  '/_protected/songbooks/': typeof ProtectedSongbooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/join/$token'
    | '/library/$songVersionId'
    | '/library/new'
    | '/songbook-catalogs/$catalogId'
    | '/songbook-catalogs/new'
    | '/songbooks/$songbookId'
    | '/songbooks/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/library/'
    | '/songbook-catalogs/'
    | '/songbooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/join/$token'
    | '/library/$songVersionId'
    | '/library/new'
    | '/songbook-catalogs/$catalogId'
    | '/songbook-catalogs/new'
    | '/songbooks/$songbookId'
    | '/songbooks/new'
    | '/teams/$teamId'
    | '/teams/new'
    | '/api/auth/$'
    | '/library'
    | '/songbook-catalogs'
    | '/songbooks'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/join/$token'
    | '/_protected/library/$songVersionId'
    | '/_protected/library/new'
    | '/_protected/songbook-catalogs/$catalogId'
    | '/_protected/songbook-catalogs/new'
    | '/_protected/songbooks/$songbookId'
    | '/_protected/songbooks/new'
    | '/_protected/teams/$teamId'
    | '/_protected/teams/new'
    | '/api/auth/$'
    | '/_protected/library/'
    | '/_protected/songbook-catalogs/'
    | '/_protected/songbooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/library/': {
      id: '/_protected/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof ProtectedLibraryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/$songVersionId': {
      id: '/_protected/library/$songVersionId'
      path: '/library/$songVersionId'
      fullPath: '/library/$songVersionId'
      preLoaderRoute: typeof ProtectedLibrarySongVersionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/new': {
      id: '/_protected/library/new'
      path: '/library/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof ProtectedLibraryNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbook-catalogs/': {
      id: '/_protected/songbook-catalogs/'
      path: '/songbook-catalogs'
      fullPath: '/songbook-catalogs/'
      preLoaderRoute: typeof ProtectedSongbookCatalogsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbook-catalogs/$catalogId': {
      id: '/_protected/songbook-catalogs/$catalogId'
      path: '/songbook-catalogs/$catalogId'
      fullPath: '/songbook-catalogs/$catalogId'
      preLoaderRoute: typeof ProtectedSongbookCatalogsCatalogIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbook-catalogs/new': {
      id: '/_protected/songbook-catalogs/new'
      path: '/songbook-catalogs/new'
      fullPath: '/songbook-catalogs/new'
      preLoaderRoute: typeof ProtectedSongbookCatalogsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbooks/': {
      id: '/_protected/songbooks/'
      path: '/songbooks'
      fullPath: '/songbooks/'
      preLoaderRoute: typeof ProtectedSongbooksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbooks/$songbookId': {
      id: '/_protected/songbooks/$songbookId'
      path: '/songbooks/$songbookId'
      fullPath: '/songbooks/$songbookId'
      preLoaderRoute: typeof ProtectedSongbooksSongbookIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/songbooks/new': {
      id: '/_protected/songbooks/new'
      path: '/songbooks/new'
      fullPath: '/songbooks/new'
      preLoaderRoute: typeof ProtectedSongbooksNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/$teamId': {
      id: '/_protected/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof ProtectedTeamsTeamIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teams/new': {
      id: '/_protected/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof ProtectedTeamsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedLibrarySongVersionIdRoute: typeof ProtectedLibrarySongVersionIdRoute
  ProtectedLibraryNewRoute: typeof ProtectedLibraryNewRoute
  ProtectedSongbookCatalogsCatalogIdRoute: typeof ProtectedSongbookCatalogsCatalogIdRoute
  ProtectedSongbookCatalogsNewRoute: typeof ProtectedSongbookCatalogsNewRoute
  ProtectedSongbooksSongbookIdRoute: typeof ProtectedSongbooksSongbookIdRoute
  ProtectedSongbooksNewRoute: typeof ProtectedSongbooksNewRoute
  ProtectedTeamsTeamIdRoute: typeof ProtectedTeamsTeamIdRoute
  ProtectedTeamsNewRoute: typeof ProtectedTeamsNewRoute
  ProtectedLibraryIndexRoute: typeof ProtectedLibraryIndexRoute
  ProtectedSongbookCatalogsIndexRoute: typeof ProtectedSongbookCatalogsIndexRoute
  ProtectedSongbooksIndexRoute: typeof ProtectedSongbooksIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedLibrarySongVersionIdRoute: ProtectedLibrarySongVersionIdRoute,
  ProtectedLibraryNewRoute: ProtectedLibraryNewRoute,
  ProtectedSongbookCatalogsCatalogIdRoute:
    ProtectedSongbookCatalogsCatalogIdRoute,
  ProtectedSongbookCatalogsNewRoute: ProtectedSongbookCatalogsNewRoute,
  ProtectedSongbooksSongbookIdRoute: ProtectedSongbooksSongbookIdRoute,
  ProtectedSongbooksNewRoute: ProtectedSongbooksNewRoute,
  ProtectedTeamsTeamIdRoute: ProtectedTeamsTeamIdRoute,
  ProtectedTeamsNewRoute: ProtectedTeamsNewRoute,
  ProtectedLibraryIndexRoute: ProtectedLibraryIndexRoute,
  ProtectedSongbookCatalogsIndexRoute: ProtectedSongbookCatalogsIndexRoute,
  ProtectedSongbooksIndexRoute: ProtectedSongbooksIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
