/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedLibraryIndexRouteImport } from './routes/_protected/library/index'
import { Route as ProtectedLibrarySongVersionIdRouteImport } from './routes/_protected/library/$songVersionId'
import { Route as ProtectedLibraryNewRouteImport } from './routes/_protected/library/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibraryIndexRoute = ProtectedLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLibrarySongVersionIdRoute =
  ProtectedLibrarySongVersionIdRouteImport.update({
    id: '/library/$songVersionId',
    path: '/library/$songVersionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLibraryNewRoute = ProtectedLibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/library/new': typeof ProtectedLibraryNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/': typeof ProtectedLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/library/new': typeof ProtectedLibraryNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library': typeof ProtectedLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/library/$songVersionId': typeof ProtectedLibrarySongVersionIdRoute
  '/_protected/library/new': typeof ProtectedLibraryNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/library/': typeof ProtectedLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/library/$songVersionId'
    | '/library/new'
    | '/api/auth/$'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/library/$songVersionId'
    | '/library/new'
    | '/api/auth/$'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/library/$songVersionId'
    | '/_protected/library/new'
    | '/api/auth/$'
    | '/_protected/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/': {
      id: '/_protected/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof ProtectedLibraryIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/$songVersionId': {
      id: '/_protected/library/$songVersionId'
      path: '/library/$songVersionId'
      fullPath: '/library/$songVersionId'
      preLoaderRoute: typeof ProtectedLibrarySongVersionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/library/new': {
      id: '/_protected/library/new'
      path: '/library/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof ProtectedLibraryNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedLibrarySongVersionIdRoute: typeof ProtectedLibrarySongVersionIdRoute
  ProtectedLibraryNewRoute: typeof ProtectedLibraryNewRoute
  ProtectedLibraryIndexRoute: typeof ProtectedLibraryIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedLibrarySongVersionIdRoute: ProtectedLibrarySongVersionIdRoute,
  ProtectedLibraryNewRoute: ProtectedLibraryNewRoute,
  ProtectedLibraryIndexRoute: ProtectedLibraryIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
